/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: com/protocol/common.proto */

#ifndef PROTOBUF_C_com_2fprotocol_2fcommon_2eproto__INCLUDED
#define PROTOBUF_C_com_2fprotocol_2fcommon_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Com__Protocol__GpsLocation Com__Protocol__GpsLocation;


/* --- enums --- */


/* --- messages --- */

struct  _Com__Protocol__GpsLocation
{
  ProtobufCMessage base;
  protobuf_c_boolean has_latitude;
  float latitude;
  protobuf_c_boolean has_longitude;
  float longitude;
  protobuf_c_boolean has_elevation;
  int32_t elevation;
  protobuf_c_boolean has_heading;
  int32_t heading;
  protobuf_c_boolean has_reversed;
  protobuf_c_boolean reversed;
};
#define COM__PROTOCOL__GPS_LOCATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__protocol__gps_location__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,0 }


/* Com__Protocol__GpsLocation methods */
void   com__protocol__gps_location__init
                     (Com__Protocol__GpsLocation         *message);
size_t com__protocol__gps_location__get_packed_size
                     (const Com__Protocol__GpsLocation   *message);
size_t com__protocol__gps_location__pack
                     (const Com__Protocol__GpsLocation   *message,
                      uint8_t             *out);
size_t com__protocol__gps_location__pack_to_buffer
                     (const Com__Protocol__GpsLocation   *message,
                      ProtobufCBuffer     *buffer);
Com__Protocol__GpsLocation *
       com__protocol__gps_location__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__protocol__gps_location__free_unpacked
                     (Com__Protocol__GpsLocation *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Protocol__GpsLocation_Closure)
                 (const Com__Protocol__GpsLocation *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__protocol__gps_location__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_com_2fprotocol_2fcommon_2eproto__INCLUDED */
