/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: com/protocol/fleet_event.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "com/protocol/fleet_event.pb-c.h"
void   com__protocol__fleet_event__position_event__init
                     (Com__Protocol__FleetEvent__PositionEvent         *message)
{
  static Com__Protocol__FleetEvent__PositionEvent init_value = COM__PROTOCOL__FLEET_EVENT__POSITION_EVENT__INIT;
  *message = init_value;
}
void   com__protocol__fleet_event__init
                     (Com__Protocol__FleetEvent         *message)
{
  static Com__Protocol__FleetEvent init_value = COM__PROTOCOL__FLEET_EVENT__INIT;
  *message = init_value;
}
size_t com__protocol__fleet_event__get_packed_size
                     (const Com__Protocol__FleetEvent *message)
{
  assert(message->base.descriptor == &com__protocol__fleet_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t com__protocol__fleet_event__pack
                     (const Com__Protocol__FleetEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &com__protocol__fleet_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t com__protocol__fleet_event__pack_to_buffer
                     (const Com__Protocol__FleetEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &com__protocol__fleet_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Com__Protocol__FleetEvent *
       com__protocol__fleet_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Com__Protocol__FleetEvent *)
     protobuf_c_message_unpack (&com__protocol__fleet_event__descriptor,
                                allocator, len, data);
}
void   com__protocol__fleet_event__free_unpacked
                     (Com__Protocol__FleetEvent *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &com__protocol__fleet_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor com__protocol__fleet_event__position_event__field_descriptors[5] =
{
  {
    "routerId",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Com__Protocol__FleetEvent__PositionEvent, has_routerid),
    offsetof(Com__Protocol__FleetEvent__PositionEvent, routerid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Com__Protocol__FleetEvent__PositionEvent, has_timestamp),
    offsetof(Com__Protocol__FleetEvent__PositionEvent, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Com__Protocol__FleetEvent__PositionEvent, location),
    &com__protocol__gps_location__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Com__Protocol__FleetEvent__PositionEvent, has_speed),
    offsetof(Com__Protocol__FleetEvent__PositionEvent, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ignition_on",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Com__Protocol__FleetEvent__PositionEvent, has_ignition_on),
    offsetof(Com__Protocol__FleetEvent__PositionEvent, ignition_on),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__protocol__fleet_event__position_event__field_indices_by_name[] = {
  4,   /* field[4] = ignition_on */
  2,   /* field[2] = location */
  0,   /* field[0] = routerId */
  3,   /* field[3] = speed */
  1,   /* field[1] = timestamp */
};
static const ProtobufCIntRange com__protocol__fleet_event__position_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor com__protocol__fleet_event__position_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.protocol.FleetEvent.PositionEvent",
  "PositionEvent",
  "Com__Protocol__FleetEvent__PositionEvent",
  "com.protocol",
  sizeof(Com__Protocol__FleetEvent__PositionEvent),
  5,
  com__protocol__fleet_event__position_event__field_descriptors,
  com__protocol__fleet_event__position_event__field_indices_by_name,
  1,  com__protocol__fleet_event__position_event__number_ranges,
  (ProtobufCMessageInit) com__protocol__fleet_event__position_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue com__protocol__fleet_event__event_type__enum_values_by_number[1] =
{
  { "POSITION", "COM__PROTOCOL__FLEET_EVENT__EVENT_TYPE__POSITION", 0 },
};
static const ProtobufCIntRange com__protocol__fleet_event__event_type__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex com__protocol__fleet_event__event_type__enum_values_by_name[1] =
{
  { "POSITION", 0 },
};
const ProtobufCEnumDescriptor com__protocol__fleet_event__event_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "com.protocol.FleetEvent.EventType",
  "EventType",
  "Com__Protocol__FleetEvent__EventType",
  "com.protocol",
  1,
  com__protocol__fleet_event__event_type__enum_values_by_number,
  1,
  com__protocol__fleet_event__event_type__enum_values_by_name,
  1,
  com__protocol__fleet_event__event_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor com__protocol__fleet_event__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Com__Protocol__FleetEvent, has_type),
    offsetof(Com__Protocol__FleetEvent, type),
    &com__protocol__fleet_event__event_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Com__Protocol__FleetEvent, position),
    &com__protocol__fleet_event__position_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned com__protocol__fleet_event__field_indices_by_name[] = {
  1,   /* field[1] = position */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange com__protocol__fleet_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor com__protocol__fleet_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "com.protocol.FleetEvent",
  "FleetEvent",
  "Com__Protocol__FleetEvent",
  "com.protocol",
  sizeof(Com__Protocol__FleetEvent),
  2,
  com__protocol__fleet_event__field_descriptors,
  com__protocol__fleet_event__field_indices_by_name,
  1,  com__protocol__fleet_event__number_ranges,
  (ProtobufCMessageInit) com__protocol__fleet_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
