/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: com/protocol/fleet_event.proto */

#ifndef PROTOBUF_C_com_2fprotocol_2ffleet_5fevent_2eproto__INCLUDED
#define PROTOBUF_C_com_2fprotocol_2ffleet_5fevent_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "com/protocol/common.pb-c.h"

typedef struct _Com__Protocol__FleetEvent Com__Protocol__FleetEvent;
typedef struct _Com__Protocol__FleetEvent__PositionEvent Com__Protocol__FleetEvent__PositionEvent;


/* --- enums --- */

typedef enum _Com__Protocol__FleetEvent__EventType {
  COM__PROTOCOL__FLEET_EVENT__EVENT_TYPE__POSITION = 0
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COM__PROTOCOL__FLEET_EVENT__EVENT_TYPE)
} Com__Protocol__FleetEvent__EventType;

/* --- messages --- */

struct  _Com__Protocol__FleetEvent__PositionEvent
{
  ProtobufCMessage base;
  protobuf_c_boolean has_routerid;
  int32_t routerid;
  protobuf_c_boolean has_timestamp;
  int32_t timestamp;
  Com__Protocol__GpsLocation *location;
  protobuf_c_boolean has_speed;
  int32_t speed;
  protobuf_c_boolean has_ignition_on;
  protobuf_c_boolean ignition_on;
};
#define COM__PROTOCOL__FLEET_EVENT__POSITION_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__protocol__fleet_event__position_event__descriptor) \
    , 0,0, 0,0, NULL, 0,0, 0,0 }


struct  _Com__Protocol__FleetEvent
{
  ProtobufCMessage base;
  protobuf_c_boolean has_type;
  Com__Protocol__FleetEvent__EventType type;
  Com__Protocol__FleetEvent__PositionEvent *position;
};
#define COM__PROTOCOL__FLEET_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__protocol__fleet_event__descriptor) \
    , 0,0, NULL }


/* Com__Protocol__FleetEvent__PositionEvent methods */
void   com__protocol__fleet_event__position_event__init
                     (Com__Protocol__FleetEvent__PositionEvent         *message);
/* Com__Protocol__FleetEvent methods */
void   com__protocol__fleet_event__init
                     (Com__Protocol__FleetEvent         *message);
size_t com__protocol__fleet_event__get_packed_size
                     (const Com__Protocol__FleetEvent   *message);
size_t com__protocol__fleet_event__pack
                     (const Com__Protocol__FleetEvent   *message,
                      uint8_t             *out);
size_t com__protocol__fleet_event__pack_to_buffer
                     (const Com__Protocol__FleetEvent   *message,
                      ProtobufCBuffer     *buffer);
Com__Protocol__FleetEvent *
       com__protocol__fleet_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__protocol__fleet_event__free_unpacked
                     (Com__Protocol__FleetEvent *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Protocol__FleetEvent__PositionEvent_Closure)
                 (const Com__Protocol__FleetEvent__PositionEvent *message,
                  void *closure_data);
typedef void (*Com__Protocol__FleetEvent_Closure)
                 (const Com__Protocol__FleetEvent *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__protocol__fleet_event__descriptor;
extern const ProtobufCMessageDescriptor com__protocol__fleet_event__position_event__descriptor;
extern const ProtobufCEnumDescriptor    com__protocol__fleet_event__event_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_com_2fprotocol_2ffleet_5fevent_2eproto__INCLUDED */
