/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: com/protocol/unitcom_message.proto */

#ifndef PROTOBUF_C_com_2fprotocol_2funitcom_5fmessage_2eproto__INCLUDED
#define PROTOBUF_C_com_2fprotocol_2funitcom_5fmessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "com/protocol/unitcom_event.pb-c.h"

typedef struct _Com__Protocol__UnitcomMessage Com__Protocol__UnitcomMessage;


/* --- enums --- */

typedef enum _Com__Protocol__UnitcomMessage__MessageType {
  COM__PROTOCOL__UNITCOM_MESSAGE__MESSAGE_TYPE__EVENT = 0
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COM__PROTOCOL__UNITCOM_MESSAGE__MESSAGE_TYPE)
} Com__Protocol__UnitcomMessage__MessageType;

/* --- messages --- */

struct  _Com__Protocol__UnitcomMessage
{
  ProtobufCMessage base;
  protobuf_c_boolean has_type;
  Com__Protocol__UnitcomMessage__MessageType type;
  size_t n_event;
  Com__Protocol__UnitcomEvent **event;
};
#define COM__PROTOCOL__UNITCOM_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__protocol__unitcom_message__descriptor) \
    , 0,0, 0,NULL }


/* Com__Protocol__UnitcomMessage methods */
void   com__protocol__unitcom_message__init
                     (Com__Protocol__UnitcomMessage         *message);
size_t com__protocol__unitcom_message__get_packed_size
                     (const Com__Protocol__UnitcomMessage   *message);
size_t com__protocol__unitcom_message__pack
                     (const Com__Protocol__UnitcomMessage   *message,
                      uint8_t             *out);
size_t com__protocol__unitcom_message__pack_to_buffer
                     (const Com__Protocol__UnitcomMessage   *message,
                      ProtobufCBuffer     *buffer);
Com__Protocol__UnitcomMessage *
       com__protocol__unitcom_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__protocol__unitcom_message__free_unpacked
                     (Com__Protocol__UnitcomMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Protocol__UnitcomMessage_Closure)
                 (const Com__Protocol__UnitcomMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__protocol__unitcom_message__descriptor;
extern const ProtobufCEnumDescriptor    com__protocol__unitcom_message__message_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_com_2fprotocol_2funitcom_5fmessage_2eproto__INCLUDED */
