/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: com/protocol/unitcom_event.proto */

#ifndef PROTOBUF_C_com_2fprotocol_2funitcom_5fevent_2eproto__INCLUDED
#define PROTOBUF_C_com_2fprotocol_2funitcom_5fevent_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "com/protocol/common.pb-c.h"

typedef struct _Com__Protocol__UnitcomEvent Com__Protocol__UnitcomEvent;
typedef struct _Com__Protocol__UnitcomEvent__DeviceStateEvent Com__Protocol__UnitcomEvent__DeviceStateEvent;
typedef struct _Com__Protocol__UnitcomEvent__VehicleStateEvent Com__Protocol__UnitcomEvent__VehicleStateEvent;
typedef struct _Com__Protocol__UnitcomEvent__ConnectionStatsEvent Com__Protocol__UnitcomEvent__ConnectionStatsEvent;
typedef struct _Com__Protocol__UnitcomEvent__FenceCrossingEvent Com__Protocol__UnitcomEvent__FenceCrossingEvent;
typedef struct _Com__Protocol__UnitcomEvent__NotifyEvent Com__Protocol__UnitcomEvent__NotifyEvent;
typedef struct _Com__Protocol__UnitcomEvent__PositionEvent Com__Protocol__UnitcomEvent__PositionEvent;


/* --- enums --- */

typedef enum _Com__Protocol__UnitcomEvent__EventType {
  COM__PROTOCOL__UNITCOM_EVENT__EVENT_TYPE__DEVICE_STATE = 0,
  COM__PROTOCOL__UNITCOM_EVENT__EVENT_TYPE__VEHICLE_STATE = 1,
  COM__PROTOCOL__UNITCOM_EVENT__EVENT_TYPE__CONNECTION_STATS = 2,
  COM__PROTOCOL__UNITCOM_EVENT__EVENT_TYPE__FENCE_CROSSING = 3,
  COM__PROTOCOL__UNITCOM_EVENT__EVENT_TYPE__NOTIFY = 4,
  COM__PROTOCOL__UNITCOM_EVENT__EVENT_TYPE__POSITION = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(COM__PROTOCOL__UNITCOM_EVENT__EVENT_TYPE)
} Com__Protocol__UnitcomEvent__EventType;

/* --- messages --- */

struct  _Com__Protocol__UnitcomEvent__DeviceStateEvent
{
  ProtobufCMessage base;
  protobuf_c_boolean has_routerid;
  int32_t routerid;
  protobuf_c_boolean has_timestamp;
  int32_t timestamp;
  char *mdn;
  char *esn;
  char *imsi;
  char *imei;
  char *iccid;
  char *prl;
  char *min;
  char *dow_status;
  char *hw_config;
};
#define COM__PROTOCOL__UNITCOM_EVENT__DEVICE_STATE_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__protocol__unitcom_event__device_state_event__descriptor) \
    , 0,0, 0,0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }


struct  _Com__Protocol__UnitcomEvent__VehicleStateEvent
{
  ProtobufCMessage base;
  protobuf_c_boolean has_routerid;
  int32_t routerid;
  protobuf_c_boolean has_timestamp;
  int32_t timestamp;
  char *vin;
  protobuf_c_boolean has_mileage;
  int32_t mileage;
  protobuf_c_boolean has_ignition;
  protobuf_c_boolean ignition;
  protobuf_c_boolean has_battery;
  float battery;
  protobuf_c_boolean has_fuel;
  float fuel;
};
#define COM__PROTOCOL__UNITCOM_EVENT__VEHICLE_STATE_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__protocol__unitcom_event__vehicle_state_event__descriptor) \
    , 0,0, 0,0, NULL, 0,0, 0,0, 0,0, 0,0 }


struct  _Com__Protocol__UnitcomEvent__ConnectionStatsEvent
{
  ProtobufCMessage base;
  protobuf_c_boolean has_routerid;
  int32_t routerid;
  protobuf_c_boolean has_timestamp;
  int32_t timestamp;
  protobuf_c_boolean has_up;
  int32_t up;
  protobuf_c_boolean has_down;
  int32_t down;
  protobuf_c_boolean has_uptime;
  int32_t uptime;
  protobuf_c_boolean has_online;
  int32_t online;
  char *type;
  protobuf_c_boolean has_signal;
  int32_t signal;
};
#define COM__PROTOCOL__UNITCOM_EVENT__CONNECTION_STATS_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__protocol__unitcom_event__connection_stats_event__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, NULL, 0,0 }


struct  _Com__Protocol__UnitcomEvent__FenceCrossingEvent
{
  ProtobufCMessage base;
  protobuf_c_boolean has_routerid;
  int32_t routerid;
  protobuf_c_boolean has_timestamp;
  int32_t timestamp;
  protobuf_c_boolean has_direction;
  protobuf_c_boolean direction;
  Com__Protocol__GpsLocation *location;
};
#define COM__PROTOCOL__UNITCOM_EVENT__FENCE_CROSSING_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__protocol__unitcom_event__fence_crossing_event__descriptor) \
    , 0,0, 0,0, 0,0, NULL }


struct  _Com__Protocol__UnitcomEvent__NotifyEvent
{
  ProtobufCMessage base;
  protobuf_c_boolean has_routerid;
  int32_t routerid;
  protobuf_c_boolean has_timestamp;
  int32_t timestamp;
  char *type;
  char *recipient;
  char *message;
  char *reason;
  Com__Protocol__GpsLocation *location;
};
#define COM__PROTOCOL__UNITCOM_EVENT__NOTIFY_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__protocol__unitcom_event__notify_event__descriptor) \
    , 0,0, 0,0, NULL, NULL, NULL, NULL, NULL }


struct  _Com__Protocol__UnitcomEvent__PositionEvent
{
  ProtobufCMessage base;
  protobuf_c_boolean has_routerid;
  int32_t routerid;
  protobuf_c_boolean has_timestamp;
  int32_t timestamp;
  Com__Protocol__GpsLocation *location;
};
#define COM__PROTOCOL__UNITCOM_EVENT__POSITION_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__protocol__unitcom_event__position_event__descriptor) \
    , 0,0, 0,0, NULL }


typedef enum {
  COM__PROTOCOL__UNITCOM_EVENT__EVENT__NOT_SET = 0,
  COM__PROTOCOL__UNITCOM_EVENT__EVENT_DEVICE_STATE = 2,
  COM__PROTOCOL__UNITCOM_EVENT__EVENT_VEHICLE_STATE = 3,
  COM__PROTOCOL__UNITCOM_EVENT__EVENT_CONNECTION_STATS = 4,
  COM__PROTOCOL__UNITCOM_EVENT__EVENT_FENCE_CROSSING = 5,
  COM__PROTOCOL__UNITCOM_EVENT__EVENT_NOTIFY = 6,
  COM__PROTOCOL__UNITCOM_EVENT__EVENT_POSITION = 7,
} Com__Protocol__UnitcomEvent__EventCase;

struct  _Com__Protocol__UnitcomEvent
{
  ProtobufCMessage base;
  protobuf_c_boolean has_type;
  Com__Protocol__UnitcomEvent__EventType type;
  Com__Protocol__UnitcomEvent__EventCase event_case;
  union {
    Com__Protocol__UnitcomEvent__DeviceStateEvent *device_state;
    Com__Protocol__UnitcomEvent__VehicleStateEvent *vehicle_state;
    Com__Protocol__UnitcomEvent__ConnectionStatsEvent *connection_stats;
    Com__Protocol__UnitcomEvent__FenceCrossingEvent *fence_crossing;
    Com__Protocol__UnitcomEvent__NotifyEvent *notify;
    Com__Protocol__UnitcomEvent__PositionEvent *position;
  };
};
#define COM__PROTOCOL__UNITCOM_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__protocol__unitcom_event__descriptor) \
    , 0,0, COM__PROTOCOL__UNITCOM_EVENT__EVENT__NOT_SET, {0} }


/* Com__Protocol__UnitcomEvent__DeviceStateEvent methods */
void   com__protocol__unitcom_event__device_state_event__init
                     (Com__Protocol__UnitcomEvent__DeviceStateEvent         *message);
/* Com__Protocol__UnitcomEvent__VehicleStateEvent methods */
void   com__protocol__unitcom_event__vehicle_state_event__init
                     (Com__Protocol__UnitcomEvent__VehicleStateEvent         *message);
/* Com__Protocol__UnitcomEvent__ConnectionStatsEvent methods */
void   com__protocol__unitcom_event__connection_stats_event__init
                     (Com__Protocol__UnitcomEvent__ConnectionStatsEvent         *message);
/* Com__Protocol__UnitcomEvent__FenceCrossingEvent methods */
void   com__protocol__unitcom_event__fence_crossing_event__init
                     (Com__Protocol__UnitcomEvent__FenceCrossingEvent         *message);
/* Com__Protocol__UnitcomEvent__NotifyEvent methods */
void   com__protocol__unitcom_event__notify_event__init
                     (Com__Protocol__UnitcomEvent__NotifyEvent         *message);
/* Com__Protocol__UnitcomEvent__PositionEvent methods */
void   com__protocol__unitcom_event__position_event__init
                     (Com__Protocol__UnitcomEvent__PositionEvent         *message);
/* Com__Protocol__UnitcomEvent methods */
void   com__protocol__unitcom_event__init
                     (Com__Protocol__UnitcomEvent         *message);
size_t com__protocol__unitcom_event__get_packed_size
                     (const Com__Protocol__UnitcomEvent   *message);
size_t com__protocol__unitcom_event__pack
                     (const Com__Protocol__UnitcomEvent   *message,
                      uint8_t             *out);
size_t com__protocol__unitcom_event__pack_to_buffer
                     (const Com__Protocol__UnitcomEvent   *message,
                      ProtobufCBuffer     *buffer);
Com__Protocol__UnitcomEvent *
       com__protocol__unitcom_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__protocol__unitcom_event__free_unpacked
                     (Com__Protocol__UnitcomEvent *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Protocol__UnitcomEvent__DeviceStateEvent_Closure)
                 (const Com__Protocol__UnitcomEvent__DeviceStateEvent *message,
                  void *closure_data);
typedef void (*Com__Protocol__UnitcomEvent__VehicleStateEvent_Closure)
                 (const Com__Protocol__UnitcomEvent__VehicleStateEvent *message,
                  void *closure_data);
typedef void (*Com__Protocol__UnitcomEvent__ConnectionStatsEvent_Closure)
                 (const Com__Protocol__UnitcomEvent__ConnectionStatsEvent *message,
                  void *closure_data);
typedef void (*Com__Protocol__UnitcomEvent__FenceCrossingEvent_Closure)
                 (const Com__Protocol__UnitcomEvent__FenceCrossingEvent *message,
                  void *closure_data);
typedef void (*Com__Protocol__UnitcomEvent__NotifyEvent_Closure)
                 (const Com__Protocol__UnitcomEvent__NotifyEvent *message,
                  void *closure_data);
typedef void (*Com__Protocol__UnitcomEvent__PositionEvent_Closure)
                 (const Com__Protocol__UnitcomEvent__PositionEvent *message,
                  void *closure_data);
typedef void (*Com__Protocol__UnitcomEvent_Closure)
                 (const Com__Protocol__UnitcomEvent *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__protocol__unitcom_event__descriptor;
extern const ProtobufCMessageDescriptor com__protocol__unitcom_event__device_state_event__descriptor;
extern const ProtobufCMessageDescriptor com__protocol__unitcom_event__vehicle_state_event__descriptor;
extern const ProtobufCMessageDescriptor com__protocol__unitcom_event__connection_stats_event__descriptor;
extern const ProtobufCMessageDescriptor com__protocol__unitcom_event__fence_crossing_event__descriptor;
extern const ProtobufCMessageDescriptor com__protocol__unitcom_event__notify_event__descriptor;
extern const ProtobufCMessageDescriptor com__protocol__unitcom_event__position_event__descriptor;
extern const ProtobufCEnumDescriptor    com__protocol__unitcom_event__event_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_com_2fprotocol_2funitcom_5fevent_2eproto__INCLUDED */
