/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cmsg.proto */

#ifndef PROTOBUF_C_cmsg_2eproto__INCLUDED
#define PROTOBUF_C_cmsg_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Cmsg Cmsg;


/* --- enums --- */


/* --- messages --- */

struct  _Cmsg
{
  ProtobufCMessage base;
  size_t n_c;
  int32_t *c;
};
#define CMSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cmsg__descriptor) \
    , 0,NULL }


/* Cmsg methods */
void   cmsg__init
                     (Cmsg         *message);
size_t cmsg__get_packed_size
                     (const Cmsg   *message);
size_t cmsg__pack
                     (const Cmsg   *message,
                      uint8_t             *out);
size_t cmsg__pack_to_buffer
                     (const Cmsg   *message,
                      ProtobufCBuffer     *buffer);
Cmsg *
       cmsg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cmsg__free_unpacked
                     (Cmsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Cmsg_Closure)
                 (const Cmsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cmsg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_cmsg_2eproto__INCLUDED */
